ffeKiosk/urls.py
from django.urls import re_path, include
from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth import views
from ffeKiosk import views as ffeKioskViews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^accounts/logout/$', views.LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'', include('kiosk.urls')),
    re_path(r'', include('profil.urls')),
    re_path(r'paypal/', include('paypal.urls')),
    re_path(r'cron/daily_routine/?$', ffeKioskViews.DailyRoutine.as_view()),
    re_path(r'cron/paypal_sync/?$', ffeKioskViews.SyncPayPalTransactions.as_view()),
]

kiosk/urls.py
from django.urls import re_path
from . import views, slackCommands, slackMessages

urlpatterns = [
	re_path(r'^$', views.start_page, name='start_page'),
	re_path(r'^imkiosk/$', views.imkiosk_page, name='imkiosk_page'),	
	re_path(r'^offeneEkListe/$', views.offeneEkListe_page, name='offeneEkListe_page'),
	re_path(r'^impressum/$', views.impressum_page, name='impressum_page'),
	re_path(r'^kontakt/$', views.kontakt_page, name='kontakt_page'),
	re_path(r'^datenschutzerklaerung/$', views.datenschutz_page, name='datenschutz_page'),
	re_path(r'^menu/$', views.home_page, name='home_page'),
	re_path(r'^menu/kauf/$', views.kauf_page, name='kauf_page'),
	re_path(r'^menu/gekauft/$', views.gekauft_page, name='gekauft_page'),
	re_path(r'^menu/kaufabgelehnt/$', views.kauf_abgelehnt_page, name='kauf_abgelehnt_page'),
	re_path(r'^menu/kontobewegungen/$', views.kontobewegungen_page, name='kontobewegungen_page'),
	re_path(r'^menu/kontobewegungen/(?P<s>\d+)/$', views.kontobewegungen_page_next, name='kontobewegungen_page_next'),
	re_path(r'^menu/einkaufsvormerkungen/$', views.einkauf_vormerk_page, name = 'einkauf_vormerk_page'),
	re_path(r'^menu/einkaufsannahme/$', views.einkauf_annahme_page, name = 'einkauf_annahme_page'),
	re_path(r'^menu/einkaufsannahme/(?P<userID>\d+)/$', views.einkauf_annahme_user_page, name='einkauf_annahme_user_page'),
	re_path(r'^menu/transaktion/$', views.transaktion_page, name = 'transaktion_page'),
	re_path(r'^menu/neuerNutzer/$', views.neuerNutzer_page, name = 'neuerNutzer_page'),
	re_path(r'^menu/einzahlung/$', views.einzahlung_page, name = 'einzahlung_page'),
	re_path(r'^menu/meineeinkaufe/$', views.meine_einkaufe_page, name = 'meine_einkaufe_page'),
	re_path(r'^menu/fillKioskUp/$', views.fillKioskUp, name = 'fillKioskUp'),
	re_path(r'^menu/inventory/$', views.inventory, name = 'inventory'),
	re_path(r'^menu/inventory/done/$', views.inventory_done, name = 'inventory_done'),
	re_path(r'^menu/statistics/$', views.statistics, name = 'statistics'),
	re_path(r'^menu/produktKommentare/$', views.produktKommentare, name = 'produkt_kommentare_page'),
	re_path(r'^menu/produktKommentieren/(?P<s>\d+)/$', views.produktKommentieren, name='produkt_kommentieren_page'),
	re_path(r'^menu/infos/$', views.anleitung, name = 'anleitung_page'),
	re_path(r'^menu/ersteSchritte/$', views.ersteSchritte, name = 'ersteschritte_page'),
	re_path(r'^menu/regelwerk/$', views.regelwerk, name = 'regelwerk_page'),
	re_path(r'^menu/rueckbuchung/$', views.rueckbuchung, name = 'rueckbuchungen_page'),
	re_path(r'^menu/rueckbuchung/(?P<userID>\d+)/$', views.rueckbuchung_user, name = 'rueckbuchungen_user_page'),
	re_path(r'^menu/slackComTest/$', views.slackComTest, name = 'slackComTest_page'),

	re_path(r'^receiveSlackCommands/$', slackCommands.receiveSlackCommands, name = 'receiveSlackCommands'),
	re_path(r'^receiveSlackMessages/$', slackMessages.receiveSlackMessages, name = 'receiveSlackMessages'),
	
]

profil/urls.py
from django.urls import re_path
from django.contrib.auth import views

from . import views as profilViews
from . import forms




urlpatterns = [
    
    #re_path(r'^accounts/login/$', views.login, name='login'),
    #re_path(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    
    re_path(r'^accounts/password/change/$', views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    re_path(r'^accounts/password/change/done/$', views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    re_path(r'^accounts/password/reset/$', views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', form_class=forms.SlackResetForm, email_template_name='registration/password_reset_message.html', subject_template_name='registration/password_reset_subject.html', ), name='password_reset'),
    re_path(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$', views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/done/$', views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    re_path(r'^accounts/password/reset/complete/$', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    re_path(r'^accounts/angestellt_bis_change/$', profilViews.angestellt_bis_change, name='angestellt_bis_change'),
    re_path(r'^accounts/angestellt_bis_changed/$', profilViews.angestellt_bis_changed, name='angestellt_bis_changed'),

    re_path(r'^accounts/personal_info_change/$', profilViews.PersonalInfoChange.as_view(), name='personal_info_change'),

    re_path(r'^accounts/registrationStatus/$', profilViews.registrationStatus.as_view(), name='registrationStatus'),
    re_path(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$', profilViews.AccountActivate.as_view(), name='account_activate'),
]

profil/models.py
from django.apps import apps
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from datetime import date
from django.contrib.auth.hashers import make_password


# Change the user manager for a case-insensitive login
class KioskUserManager(UserManager):
    def get_by_natural_key(self, username):
        case_insensitive_username_field = '{}__iexact'.format(self.model.USERNAME_FIELD)
        return self.get(**{case_insensitive_username_field: username})

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError("The given username must be set")
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user


class KioskUser(AbstractUser):

    objects = KioskUserManager()
    REQUIRED_FIELDS = []

    email = None
    is_verified = models.BooleanField(default=False)
    
    slackName = models.CharField(max_length=40, unique=True, help_text='Slack ID oder Name hinter @, falls keine '
                                                                       'Leerzeichen oder Umlaute.')
    paypal_name = models.CharField(max_length=64, null=True, blank=True,
                                   help_text='Name, der bei PayPal nach außen zu sehen ist')
    aktivBis = models.DateField(default=date.today)
    instruierterKaeufer = models.BooleanField(default=False)
    visible = models.BooleanField(default=True, help_text='Bank, Dieb, usw. sollen nicht gesehn und nicht angewaehlt '
                                                          'werden duerfen, z.B. bei Einkauf-Annahme')  
    activity_end_msg = models.IntegerField(
        default=0, 
        help_text="0: Active, nothing sent. 1: Active, message sent that in 7 days, account will be blocked. "
                  "2: Inactive, invisible, Inactivity message sent. 3: Account is now unpersonalised, money is "
                  "donated to Kiosk"
    )

    dsgvo_accepted = models.BooleanField(default=False)
    is_functional_user = models.BooleanField(default=False, help_text='Set to true, if this is no real user, but System user')

    class Meta:
        default_manager_name = 'objects'
        permissions = (
            ("do_admin_tasks", "Kontaktnachrichten, Statistiken, Erweiterte Produktverwaltung, Nutzerverwaltung"),
            ("do_verwaltung_product_operations", "Besorgungen annehmen, Einkäufe rückbuchen, Inventur durchführen"),
            ("do_verwaltung_financial_operations", "Einzahlungen, Auszahlungen und Geldtransaktionen abwickeln"),
            ("do_verwaltung_product_management", "Produktlisten und -preise pflegen"),
            ("do_einkauf", "Produkte vormerken und besorgen"),
            ("perm_kauf", "Einkaufen im Kiosk"),
        )

profil/views.py
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views import View
from django.contrib.auth.decorators import login_required
from kiosk.models import Kiosk, Einkaufsliste
from datetime import datetime
from django.contrib.auth.models import Group
from kiosk.models import Kontostand
from django.db import transaction
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import KioskUser
from .forms import AktivBisChangeForm, PersonalInfoChangeForm

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from profil.tokens import account_activation_token
from kiosk.bot import slack_PostWelcomeMessage


@login_required
def angestellt_bis_change(request):

    usr = KioskUser.objects.get(id=request.user.id)

    if request.method == "POST":

        aktivBisChangeForm = AktivBisChangeForm(request.POST)

        if aktivBisChangeForm.is_valid():
            date = aktivBisChangeForm.cleaned_data.get('aktivBis')
            usr.aktivBis = date
            
            # Remove the flag that (maybe) user has been warned about the end of active account
            usr.activity_end_msg = 0
            
            usr.save()

            request.session['angestellt_bis_change'] = datetime.strftime(date,'%d.%m.%Y')
            return HttpResponseRedirect(reverse('angestellt_bis_changed'))

        else:
            aktivBisChangeForm = AktivBisChangeForm(request.POST)

    else:
        aktivBisChangeForm = AktivBisChangeForm(initial={'aktivBis':usr.aktivBis,})
    
    # Hole den Kioskinhalt
    kioskItems = Kiosk.getKioskContent()

    # Einkaufsliste abfragen
    einkaufsliste = Einkaufsliste.getEinkaufsliste()

    return render(request, 'profilVerwaltung/angestellt_bis_change.html', 
        {'aktivBisChangeForm': aktivBisChangeForm, 'kioskItems': kioskItems, 'einkaufsliste': einkaufsliste,})


@login_required
def angestellt_bis_changed(request):

    # Hole den Kioskinhalt
    kioskItems = Kiosk.getKioskContent()

    # Einkaufsliste abfragen
    einkaufsliste = Einkaufsliste.getEinkaufsliste()

    if 'angestellt_bis_change' in request.session.keys():
        newDate = request.session['angestellt_bis_change']
        del request.session['angestellt_bis_change']
    else:
        return HttpResponseRedirect(reverse('home_page'))

    return render(request, 'profilVerwaltung/angestellt_bis_changed.html', 
        {'newDate': newDate, 'kioskItems': kioskItems, 'einkaufsliste': einkaufsliste,})


class PersonalInfoChange(LoginRequiredMixin, View):
    """"""

    def get(self, request):
        usr = KioskUser.objects.get(id=request.user.id)
        personal_info_change_form = PersonalInfoChangeForm(instance=usr)
        return render(request,
                      'profilVerwaltung/personalInfoChange.html',
                      dict(form=personal_info_change_form,))

    def post(self, request):
        usr = KioskUser.objects.get(id=request.user.id)
        personal_info_change_form = PersonalInfoChangeForm(request.POST, instance=usr)
        if personal_info_change_form.is_valid():
            personal_info_change_form.save()
            return render(request,
                          'profilVerwaltung/personalInfoChange.html',
                          dict(form=personal_info_change_form,
                               msg='Änderungen gespeichert',
                               color='success'))
        else:
            return render(request,
                          'profilVerwaltung/personalInfoChange.html',
                          dict(form=personal_info_change_form,
                               msg='Fehler!',
                               color='danger'))


# After Login, check, if the user is accepted to access to the page by the site admin. Redirect, if allowed. If not, messages are provided here.
class registrationStatus(LoginRequiredMixin, View):

    def get(self, request):

        if request.user.is_authenticated:
            
            if 'just_verified' in request.session.keys():
                just_verified = request.session['just_verified']
                del request.session['just_verified']
            else:
                just_verified = False
            
            if KioskUser.objects.filter(username=request.user.username,is_verified=True).exists() and not just_verified:
                
                return HttpResponseRedirect(reverse('home_page'))

            else:                
                # Get the Administrator
                data = KioskUser.objects.filter(groups__permissions__codename__icontains='do_admin_tasks')
                admins = []
                for item in data:
                    admins.append(item.first_name + ' ' + item.last_name)
                admins = ', '.join(admins)
                
                # Hole den Kioskinhalt
                kioskItems = Kiosk.getKioskContent()

                # Einkaufsliste abfragen
                einkaufsliste = Einkaufsliste.getEinkaufsliste()

                return render(request, 'registration/registrationStatus.html',{
                    'just_verified': just_verified,
                    'admins': admins,
                    'kioskItems': kioskItems, 
                    'einkaufsliste': einkaufsliste,
                })

        else:
            return HttpResponseRedirect(reverse('start_page'))


# Verify the slack name on registration. When the token, given in the verification message is correct, the corresponding flag is set to True. A Slack-message will be sent to give further information: Welcome message
class AccountActivate(View):

    @transaction.atomic
    def get(self, request, uidb64, token):

        # Check, if the address is valid
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = KioskUser.objects.get(pk=uid)

        except(TypeError, ValueError, OverflowError, KioskUser.DoesNotExist):
            user = None

        # Set the flag to be email verified and save
        if user is not None and account_activation_token.check_token(user, token):
            user.is_verified = True
            user.save()

            g = Group.objects.get(name='Nutzer')
            g.user_set.add(user)
            h = Group.objects.get(name='Einkaufer')
            h.user_set.add(user)

            k = Kontostand(nutzer_id = user.id, stand=0)
            k.save()

            # Send an slack message with further information: Welcome
            slack_PostWelcomeMessage(user)            

            # Add the information: Just email verified -> For text display on the following website
            request.session['just_verified'] = True
            messages.success(request, 'Dein Account wurde erfolgreich aktiviert. Du kannst dich nun einloggen und den Kiosk nutzen.')

            return HttpResponseRedirect(reverse('registrationStatus'))

        else:
            # Get the Administrator
            data = KioskUser.objects.filter(groups__permissions__codename__icontains='do_admin_tasks')
            admins = []
            for item in data:
                admins.append(item.first_name + ' ' + item.last_name)
            admins = ', '.join(admins)

            return render(request, 'registration/verification_failed.html',{
                    'admins': admins,
                })

profil/templates/profilVerwaltung/angestellt_bis_change.html
{% extends 'kiosk/base.html' %}

{% load widget_tweaks %}    

{% block content %}


    <div class="page-header noMarginTop">
        <h4>Datum der Kontodeaktivieren</h4>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading bold">
            Warum sollte ich mein Austrittsdatum aus der FfE korrekt einstellen?
        </div>
        <div class="panel-body justified smallText">
            Nach diesem Datum kannst du keine Eink&#228;ufe im FfE-Kiosk t&#228;tigen und dein Konto wird deaktiviert.
            Durch Einstellen dieses Datums bekommst du automatisch rechtzeitig vor dem Ende deiner Besch&#228;ftigungszeit eine Slack-Nachricht, die dich daran erinnert, entweder dein Guthaben auszahlen zu lassen oder deine Besch&#228;ftigungszeit zu verl&#228;ngern.
        </div>  
    </div>

    <form method="post">
        {% csrf_token %}

        {% for field in aktivBisChangeForm %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field | add_class:"form-control" }}
                <br>
                {% if field.errors %}
                    <p class="alert alert-danger">{{ field.errors.as_text }}</p>
                {% endif %}
                {% if field.help_text %}
                    <p class="alert alert-info">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        
        <input type="submit" class="btn btn-primary" value="Datum &#228;ndern" />  
    </form>


    <hr>
    <a class="bigLink" href="{% url 'home_page' %}">zur&#252;ck zum pers&#246;nlichen Bereich</a><br>

{% endblock %}

{% block javascript %}

    <script type="text/javascript">
        $(document).ready(
            function(){
                $('.datepicker').datepicker({
                    language: 'de',
                    format: 'dd.mm.yyyy',
                    todayHighlight: true,
                    startDate: '-3d'
                });
            }
        );
    </script>

{% endblock %}

profil/templates/profilVerwaltung/angestellt_bis_changed.html
{% extends 'kiosk/base.html' %}	

{% block content %}

    <div class="page-header noMarginTop">
        <h4>Datum der Kontodeaktivieren <small>Erfolg!</small></h4>
    </div>

    <p class="alert alert-success">
    	Das Datum der Deaktivierung deines Kontos wurde erfolgreich auf {{ newDate }} eingestellt.
    </p>


    <hr>
    <a class="bigLink" href="{% url 'home_page' %}">zur&#252;ck zum pers&#246;nlichen Bereich</a><br>

{% endblock %}

profil/templates/profilVerwaltung/personalInfoChange.html
{% extends 'kiosk/base.html' %}

{% load static %}
{% load widget_tweaks %}    

{% block content %}

    <div class="page-header noMarginTop">
        <h4>Persönliche Informationen ändern</h4>
    </div>

    {% if msg != '' and msg != None %}
		<div id="message">
		{% if color == 'danger' %}
			<p class="alert alert-danger">
				{{msg}}
			</p>
		{% elif color == 'success' %}
			<p class="alert alert-success">
				{{msg}}
			</p>
		{% else %}
			<p class="alert alert-info">
				{{msg}}
			</p>
		{% endif %}
		</div>
	  {% endif %}

    <form method="post">
        {% csrf_token %}

			  {{ form.non_field_errors }}

        {% for field in form %}
            <div class="form-group">
                {% if field.name == 'slackName' %}
                	{{ field.label_tag }}
                	<br>
                	{{ field | add_class:"form-control slackName" }}
                	&nbsp;
                	<a name="buttonVerbindungTesten" class="btn btn-default slackName">Verbindung testen</a>
                	&nbsp;
                	<div name="VerbindungTestenErgebnis" class="slackName">
                	</div>

                {% else %}
                	{{ field.label_tag }}
                	{{ field | add_class:"form-control" }}
                {% endif %}

                <br>
                {% if field.errors %}
                	<p class="alert alert-danger">{{ field.errors.as_text }}</p>
                {% endif %}
                {% if field.help_text %}
										{% if field.name == 'slackName' %}
											<!-- Button trigger modal -->
											<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
												Infos zur Slack-Integration
											</button>
										{% endif %}
										{% if field.name == 'paypal_name' %}
											<!-- Button trigger modal -->
											<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">
												Infos zur PayPal-Integration
											</button>
										{% endif %}
                    <p class="alert alert-info">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        <input type="submit" class="btn btn-primary" value="Speichern" />
    </form>

    <hr>
    <a class="bigLink" href="{% url 'home_page' %}">zur&#252;ck zum pers&#246;nlichen Bereich</a><br>

{% endblock %}


{% block modal_title %}
	Infos zur Slack Integration
{% endblock %}
{% block modal_body %}
	<p>
		Eine funktionierende Verbindung zu deinem Slack-Account ist notwendig, um die Registrierung erfolgreich durchzuführen.
		Deshalb nutze bitte <b>"Verbindung testen",</b> um zu prüfen, ob der eingegebene User existiert und erreichbar ist.
	</p>
	<p>
		Sollte eine Verbindung mit dem Nutzernamen nicht möglich sein, da der Name Leerzeichen oder Sonderzeichen besitzt,
		musst du deine User-ID nutzen. Diese kannst du folgendermaßen beschaffen:
	</p>

	<p>
		Klicke in Slack links unten auf deinen User und dann auf dein Profil.<br />
		<img src="{% static 'img/slack-help-1.png' %}" style="opacity: 1; width: 100%; max-width: 300px;" />
	</p>
	<p>
		Rechts öffnet sich das Profil und du öffnest das erweiterte Menü bei den drei Punkten.<br />
		<img src="{% static 'img/slack-help-2.png' %}" style="opacity: 1; width: 100%; max-width: 300px;" />
	</p>
	<p>
		Hier findest du die Mitglieds-ID bzw. Member-ID, die du kopieren und einfügen kannst. Bitte nochmals testen, ob es funktioniert.<br />
		<img src="{% static 'img/slack-help-3.png' %}" style="opacity: 1; width: 100%; max-width: 300px;" />
	</p>
{% endblock %}

{% block modal_title_2 %}
	Infos zur PayPal Integration
{% endblock %}
{% block modal_body_2 %}
	<p>
		Wenn du dein Guthaben via PayPal aufladen möchtest, musst du deinen PayPal Namen hier eintragen. Anderweitig
		können wir eine Überweisung auf das Kiosk PayPal Konto nicht dir zuordnen und du musst dich bei einem Admin melden.
	</p>
	<p>
		Deinen PayPal Namen, den wir benötigen, findest du folgendermaßen:
	</p>

	<p>
		Klicke oben rechts auf das Einstellungen-Symbol.<br />
		<img src="{% static 'img/paypal-help-1.png' %}" style="opacity: 1; width: 100%; max-width: 300px;" />
	</p>
	<p>
		Links erscheint dein Name. Dieser wird benötigt.<br />
		<img src="{% static 'img/paypal-help-2.png' %}" style="opacity: 1; width: 100%; max-width: 300px;" />
	</p>
{% endblock %}

{% block javascript %}

    <!-- Initialisation for the ajax post requests -->
	<script type="text/javascript" src="{% static 'js/ajax_csrf_prepare.js' %}"></script>

	<!-- Function to post a connection try to a Slack account to the server -->
	<script type="text/javascript">

		function postSlackAccountCheck() {
			var slackName = $("input#id_slackName").val();

			$.ajax({
				type: 'POST',
				url: "{% url 'neuerNutzer_page' %}",
				data: {'what': 'testSlackName','slackName': slackName},
				dataType: 'json',
				error: function(jqXHR, textStatus, errorThrown){
							$("div#loaderPower").css('display','none');
							var msg = 'Es gab einen Fehler mit Fehlercode '+jqXHR.status+': "'+errorThrown+'".'
							$("div[name='VerbindungTestenErgebnis']").html(msg);
				},
				success: function(data){
							$("div[name='VerbindungTestenErgebnis']").html(data['data']);
						}
			});
		}
		$(document).ready(
			function(){
				$("a[name='buttonVerbindungTesten']").click(postSlackAccountCheck);

				setTimeout(() => {
					$('#message').fadeOut('slow')
				}, 3000)
			}
		);
  </script>

	<style type="text/css">
		.slackName {
			display: inline-block;
			/*min-width: 100px;*/
			width: initial;
		}
		.alert-small {
			padding-bottom: 7px;
			padding-top:5px;
		}
	</style>

{% endblock %}